install.packages("sqldf")
library(sqldf)
data <- read.csv.sql( file ="household_power_consumption.txt", header = TRUE, sep=";", sql = "select * from file where Date in ('1/2/2007','2/2/2007')")
data$DateTime = strptime(x = paste( data$Date, data$Time), format = "%d/%m/%Y %H:%M:%S")
png( filename = "plot3.png", width=480, height = 480, units = "px")
plot( data$DateTime, data$Sub_metering_1, type ="l", col= "BLACK" , ylab = "Energy sub metering", xlab="")
lines(data$DateTime, data$Sub_metering_2, col="RED", type="l" )
lines(data$DateTime, data$Sub_metering_3, col="BLUE", type="l" )
legend("topright" , legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("BLACK","RED","BLUE"), lwd=1)
dev.off()